"""add review table

Revision ID: eeac7632537d
Revises: 4dda43a29855
Create Date: 2024-04-04 16:12:58.335050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeac7632537d'
down_revision = '4dda43a29855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['name'])
    op.create_unique_constraint(None, 'items', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
